### ISSUE TITLE
Bugsnag conflict

### ISSUE THREAD

**Issue by ppamorim** [Ereza/CustomActivityOnCrash#12]
Hi.
I noticed that library is blocking the crash analysis Bugsnag. I initialize the Bugsnag after the install of CustomActivityOnCrash. But still not notifies the bugs.

The application class:

     @Override public void onCreate() {
        super.onCreate();
        initializeDependencyInjector().inject(this);
        CustomActivityOnCrash.setEnableAppRestart(true);
        CustomActivityOnCrash.setShowErrorDetails(true);
        CustomActivityOnCrash.setErrorActivityClass(CustomErrorActivity.class);
        CustomActivityOnCrash.install(this);
        ActiveAndroid.initialize(this);
        Fresco.initialize(getApplicationContext());
        FacebookSdk.sdkInitialize(this);
        Bugsnag.init(this);
      }

I removed the install and Bugsnag comes working.

**Comment by Ereza** [comment]
Hi:

This is probably a concurrency issue with Bugsnag, they call back to the default handler, which makes CustomActivityOnCrash work, but they send the crash to their server on an asynchronous thread. If the sending fails, then they store it on disk for the next iteration.

If CustomActivityOnCrash is launched first (it's likely, because it's on the main thread), it kills the app and of course the asynchronous thread launched by Bugsnag is killed too.

What they should do (and I think that's what Crashlytics and ACRA do) is just write to disk on the main thread, then launch the new thread to their server. If the thread fails, it will be sent on the next app restart.

Actually you could probably fix this by making their ExceptionHandler call Client.notify(error, true) to make it blocking and do their things on the main thread. However, I can't verify that since I don't have a Bugsnag account.

I would suggest submitting a bug report or pull request to Bugsnag to fix this issue. This can also happen on their project with a default exception handler that just kills the app (that's what CustomActivityOnCrash ends up doing).

If you can't change the Bugsnag code, you can create a custom UnhandledExceptionHandler that calls back to the original handler, and set it after installing CustomActivityOnCrash. There, you can report a handled exception and wait for some milliseconds to give time for Bugsnag to process it. It's not the most elegant of solutions but it can be a workaround.

Check these classes if you want to take a deeper look at it:
https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/Bugsnag.java (initializes the client)
https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/Client.java (initializes the exception handler and does the send logic)
https://github.com/bugsnag/bugsnag-android/blob/master/src/main/java/com/bugsnag/android/ExceptionHandler.java (the actual exception handler)

I'll close this issue because there is nothing that the library can do to fix this problem. If you find out anything that could make this library handle better these situations please comment again and I'll reopen it.
