### ISSUE TITLE
Found memory leak via LeakCanary...

### ISSUE THREAD

**Issue by sirvon** [Ereza/CustomActivityOnCrash#13]
This leak is popping up via LeakCanary.....

![screenshot_2015-08-12-13-53-04](https://cloud.githubusercontent.com/assets/1570089/9232325/01fcc244-40fb-11e5-92db-49d576fbb897.png)

**Comment by sirvon** [comment]
oh and btw this library is freaking awesome!!@#!

**Comment by Ereza** [comment]
@sirvon Thanks for the report! Do you have any idea of where the leak appears to be? The screenshot doesn't provide much info to me. My only idea could be in the `OnClickListener`s, because they hold a reference to the activity... But when the activity is destroyed they will also be destroyed, so I don't see any leak there.

Anyway, leaks in the error activity are not that problematic, since the app is completely killed when clicking the "Restart" button, thus freeing all memory. But if there is one, I'd like to fix it!

**Comment by Ereza** [comment]
Closing due to lack of feedback. If you can provide an explanation of why the leak is happening, I'll reopen it!
