### ISSUE TITLE
Add send report to email

### ISSUE THREAD

**Issue by hamzux** [Ereza/CustomActivityOnCrash#16]
Hello, 
Thank you for your nice library. 
How can I add a "send report by email" button instead of show error details?

**Comment by Ereza** [comment]
Hi, sorry for the late reply. The best way would be to copy the default error activity in the library to your project, and modify it as needed. Then you can just use `CustomActivityOnCrash.setErrorActivityClass(YourErrorActivity.class);` to set the library to use your activity instead of the default one.

If you do this, make sure to read the full documentation (see https://github.com/Ereza/CustomActivityOnCrash/blob/master/README.md), because you need to implement it in a certain way (add a custom process to the activity, restart the app using the library methods, etc.)

Since this is a feature that some people could also like, feel free to send a pull request if you wish!
