### ISSUE TITLE
Trace loggin

### ISSUE THREAD

**Issue by karathb** [Ereza/CustomActivityOnCrash#18]
Just a note, that stack trace logging is not working, because of the "\n\n" before it. So if you call CustomActivityOnCrash.getAllErrorDetailsFromIntent(context, intent) and log the result, it ends after the device modell name. If you remove the "\n\n" from the end of this part of the string, it is working

**Comment by Ereza** [comment]
Fixed in 1.5.0 by adding a space between the two line feeds, this appears to be a limitation in LogCat. However, I should try to remove this method for 2.0, since it is tightly coupled with the presentation in the default error activity. Ideally, it should be a bean and the error activity should format it as needed.

Thanks for your bug report!
