### ISSUE TITLE
Auto restart app consecutive ?

### ISSUE THREAD

**Issue by AndroidLTG** [Ereza/CustomActivityOnCrash#19]
I create a App launcher and add CustomActivityOnCrash be like sample.
But when i get error, this app restart consecutive.
Not show the layout error .

**Comment by Ereza** [comment]
Hi @AndroidLTG, I have actually used the library in a launcher application and it works as expected.
However, I imagine that your case is also one I have met before: if you do something that crashes in a background thread in your Application class, the app will enter a restart loop with the current version of the library (1.4.0). I am trying to fix this for 1.5.0, by setting a shared preference and defaulting to the default Android error screen if the last crash occurred less than 2 seconds ago. This should solve most  restart loops, but everything that is invoked in a background thread from the Application class is likely to cause restart loops in case of crashes...

**Comment by Ereza** [comment]
Fixed in 1.5.0 with a shared preference. When a crash occurs, the current timestamp is saved into it. If a new crash occurs in less than 2 seconds, the library assumes that it's a restart loop and just defaults to the system exception handler ("App X has stopped.").

If you encounter this bug again and can provide a little sample to reproduce it, please let me know!

**Comment by AndroidLTG** [comment]
It save my day ! Thanks very much !
