### ISSUE TITLE
I got a quesion.

### ISSUE THREAD

**Issue by linchangjian** [Ereza/CustomActivityOnCrash#22]
This library can't catch ANR ,  I regret to say.  Have you studied about it?

**Comment by Ereza** [comment]
There is no easy way to detect ANR, but you can try using this library: https://github.com/SalomonBrys/ANR-WatchDog

It will work with CustomActivityOnCrash since it throws a runtime exception when an ANR is detected.
However, I have never used it and I don't know what are the implications of using it (possibly more CPU and battery usage?).

If at any time ANR become detectable by the framework itself, I will add support for that, of course.
