### ISSUE TITLE
Launch activity when in background flag not always working

### ISSUE THREAD

**Issue by Sloy** [Ereza/CustomActivityOnCrash#24]
Hi!

I recently added the flag `setLaunchErrorActivityWhenInBackground(false)` to avoid showing the error activity when the user is not using the app. For what I've seen it only work sometimes.

If I force a crash in a Receiver and send a broadcast from the terminal with adb, sometimes the error activity shows up and sometimes it doesn't. 

I've been trying to understand the code that makes this "background error" flag work and it looks fine, I'm not sure what is going on. 

Do you have any knowledge of this issue? If you want we can investigate some more.

Thank!

**Comment by Ereza** [comment]
Hi! Thanks for the feedback!

I didn't know about this issue, but it could be possible. I have seen two reports on the Google Developer Console for my apps, which should not be there because CustomActivityOnCrash never calls the system's `UncaughtExceptionHandler`. However, they didn't show up in Crashlytics either.

When it happened to you, did the system error window launch? And I don't think so, but is your receiver somehow running in another process aside from the main app process?

If you can provide a simple example showing how to reproduce it (even if it only happens sometimes and is not always reproducible), I can take a look into it.

**Comment by Sloy** [comment]
Hi @Ereza, sorry for the (very) late response. I could not reproduce it and lately for what I've seen this feature has been working fine. 
So I'm closing the issue and will let you know if I encounter the problem again.
Thanks for everything!
