### ISSUE TITLE
Build date is zero'd out

### ISSUE THREAD

**Issue by JTBrinkmann** [Ereza/CustomActivityOnCrash#31]
Apparently newer gradle versions (possibly 2.2.0+ ?) set the timestamp of all files in the compiled APK to Fri, Nov 30 1979 00:00:00 (312764400000) making the Build date information useless. This can be detected by comparing the build date to `312764400000` and it can be fixed by determining build date using `packageInfo.lastUpdateTime` (requires API 9+), similar to how the `versionName` is retreived. Alternatively gradle can be configured to use proper timestamps on files by setting `android.keepTimestampsInApk = true` in the gradle.properties.

see also:
https://code.google.com/p/android/issues/detail?id=220039
http://stackoverflow.com/questions/7607165

**Comment by Ereza** [comment]
Hi @JTBrinkmann, and sorry for the long delay in my response.

Thanks for the PR. Unfortunately, `packageInfo.lastUpdateTime` does not report the build date but the install date. I have made build date an optional field (it is not shown if the build date is not present or older than 312764400000), but the only way to get the build date showing is using `android.keepTimestampsInApk = true` as you pointer out.

I will reject the PR because of this, but thanks for your time anyway. Feel free to provide any other improvement in the future.

This will be published in version 2.0.0 of the library, which I'll publish soon.

**Comment by Ereza** [comment]
The latest version is now on Maven Central.
