### ISSUE TITLE
request: Send Intent data to custom Crash Screen

### ISSUE THREAD

**Issue by android-dataticket** [Ereza/CustomActivityOnCrash#36]
With this library, I have a custom crash screen that displays an activity and sends an email to me.  I try to grab one global variable that is stored in my Application class, but the variable is null - it appears the Application class is being destroyed before the custom crash screen is displayed.

Is there a way that you could add support to add intent data or otherwise store a variable in the library so when the application crashes, the custom crash screen has access to this variable (in my case it's just a string that I need)

thank you !

**Comment by Ereza** [comment]
Hi @android-dataticket, thanks for the suggestion! What you described is indeed the normal behavior, the Application class is destroyed because a new app process is started and the previous one is killed.

I'll take a look to see if it is feasible to add some custom data to the Intent, so it becomes available to the ErrorActivity once the app is restarted.

**Comment by android-dataticket** [comment]
Thank you for the reply! I ended up deciding it's best to store my variable as a shared preference, so no need to add any special intent data.. I'm sure it's best to handle with shared preference anyways. 

Thanks again for the sweet library!

**Comment by Ereza** [comment]
Closing this for now since I don't feel like this is something that the library should do. As you already explained, the best way is to save this on the app code side (shared preferences, database, etc.) and use a custom error activity if needed to recover the data.

Thanks for your report.
