### ISSUE TITLE
Request: Capture ANR state of thread

### ISSUE THREAD

**Issue by gbatra24** [Ereza/CustomActivityOnCrash#47]
Currently, libraries like ACRA, Crashlytics, Hockey, etc do not capture ANR(Application not responding). It will be very helpful if we can intercept ANR and listen it

**Comment by Ereza** [comment]
Hi @gbatra24, thanks for the suggestion. However, capturing ANR is not possible since Android does not let the app know if there has been an ANR.

There is a possible solution you can use: @SolomonBrys has created an awesome library that tries to catch ANRs and you can even report them to your crash reporting tool: https://github.com/SalomonBrys/ANR-WatchDog

However, I have not used it and I am unsure if it might have some effect on battery usage or cause other issues with your app. But you can consider trying it ;)

I'll close this since there are no current plans to reimplement ANR-WatchDog's functionality inside CustomActivityOnCrash. However, if anyone wants to send a PR, feel free to do it :P
