### ISSUE TITLE
CustomActivityOnCrash(V 2.2.0) Not work when use ACRA!

### ISSUE THREAD

**Issue by RTDeveloperman** [Ereza/CustomActivityOnCrash#49]
hi @Ereza 
i try to use your Lib in my project but when I use
` Acra .init(this)`
in application Class, CustomActivityOnCrash not work.

` @Override
    public void onCreate() {
        super.onCreate();
        CaocConfig.Builder.create() .showErrorDetails(false) .apply();
        context = getApplicationContext();
        // The following line triggers the initialization of ACRA
        ACRA.init(this);
        ACRA.getErrorReporter().putCustomData("IMEI", getIMEI(this));

        if (!InitPublicClass.getInstance(this).initPublicClass()) {
            System.exit(0);
        }
    }`

**Comment by Ereza** [comment]
Hi @RTDeveloperman, thanks for reporting this.

What version of ACRA are you using? Also, what are the contents of the `@ReportsCrashes` annotation?

**Comment by errahby** [comment]
Same problem here!

**Comment by Ereza** [comment]
Hi, sorry for the late reply.

Just tested it with ACRA 5.3.2. Many things have changed in ACRA since the last release of this library. In order to make it work together with CustomActivityOnCrash, you must:

* Call `ACRA.init()` inside `Application.onCreate`, **NOT** `Application.attachBaseContext`.
* Enable `alsoReportToAndroidFramework` to `true` in the ACRA configuration.

This will be available in the next release of the library. Please let me know if you experience any other issues.
