### ISSUE TITLE
Not working with firebase Crashlytics 

### ISSUE THREAD

**Issue by razi3742** [Ereza/CustomActivityOnCrash#75]
i just integrated firebase crashlytics 

implementation 'com.google.firebase:firebase-crashlytics:17.0.0'

then i observed its not working. 

if i commented this line FirebaseCrashlytics.getInstance().setCrashlyticsCollectionEnabled(true) then custom crash works. 
note: i am initializing this in appliction onCreate Method

**Comment by monossido** [comment]
In my experience is Firebase Crashlytics not  working if CustomActivityOnCrash is installed.

Firebase Crashlytics cannot catch the crash event, how to solve this?

**Comment by akinsetesunday** [comment]
@monossido The issue it's having with firebase is because the default error activity of this library cat.ereza.customactivityoncrash.activity.DefaultErrorActivity is started in another process. So FirebaseCrashlytics throws an error that firebase is not initialized in the new process. 

You can declare your own custom error activity and pass it in 

.errorActivity() //default: null (default error activity)

As long as the crash is not coming from you Application class this will work.

**Comment by Ereza** [comment]
Your custom error activity should always be set to use another process as stated in the documentation. Not doing so will make the app hang or produce unexpected behavior when a crash occurs.

The solution in order to make Firebase Crashlytics work normally in the new process is to call `FirebaseApp.initializeApp(this);` in your `Application`'s class `onCreate`. This will be detailed in the installation instructions from now on.
