### ISSUE TITLE
Plagiarism of your library

### ISSUE THREAD

**Issue by jakoss** [Ereza/CustomActivityOnCrash#76]
Hi,

This is not an issue with the library itself, more like discussion about plagiarism of one individual. He copied your code basically 1 to 1 (even readme is like 99% the same as here), changed the UI (to REALLY ugly one) and added section "Hire me". I'm not sure about the legality of this, but i think you might want to know.

Repo: https://github.com/TutorialsAndroid/crashx

**Comment by Ereza** [comment]
Thanks for letting me know about this. I have not updated the library for quite a long time as I am not fully into Android development anymore (I still plan to update it in the near future however).

Of course, anyone can use and modify the code as long as they comply with the Apache License, which in this case they do not because they don't even mention me anywhere. Unfortunately, there is little I can do to keep this from happening, and I will not begin a (possibly costly) legal dispute over a non-profit library (and they probably know that, that's why they plagiarise code).

Thanks anyway for your kindness in sharing this! I'll close the issue because I don't think there is anything I can do to avoid this.
