### ISSUE TITLE
Is it possible to show a fragment instead of activity for crashes?

### ISSUE THREAD

**Issue by Morteza-Rastgoo** [Ereza/CustomActivityOnCrash#78]
I have a single activity based application which uses navigation components to switch between fragments. So every page is a fragment!
I need to show this error page as a fragment in my single activity.

What i need is:
1- Add crash page as fragment to my navigation graph and navigate to it.
2- Navigate to another fragment from your crash fragment with user action(Send user to support page to past the stack trace and guide the user).

Is there any possibility to do this?

**Comment by Ereza** [comment]
It's not possible because when an app crash occurs, the process gets killed by the system. You can only launch a new Intent (that's what this library does). You could change this intent to launch a custom error activity of your own (that could be your main activity with some code to display your own error fragment), but it's impossible to keep the back stack or any state from your old activity.
