### ISSUE TITLE
Not works with FirebaseFirestore

### ISSUE THREAD

**Issue by aakumykov** [Ereza/CustomActivityOnCrash#80]
Hi. CAOC not works if custom Application class has field initialized with FirebaseFirestore singleton instance. Regardless of manual initialization with CaocConfig.Builder.

Sample app to demonstrate problem. See MyApp onCreate() method.
[https://github.com/aakumykov/caoc_firebasefirestore_conflict](https://github.com/aakumykov/caoc_firebasefirestore_conflict)

**Comment by Ereza** [comment]
Thanks for the report and taking your time to provide an example. I am not fully into Android development anymore, but I still plan to take a look into this in the near future. I'll keep you updated!

**Comment by hardikm9850** [comment]
Hey @Ereza @aakumykov 
Were you guys able to get it work with Firebase?

@Ereza : Appreciate your effort on this helpful lib.

**Comment by Ereza** [comment]
Hi there,

I am unable to run the sample project because is lacks google-services.json, as stated in the logs when running the app:

`W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.`

However, sample aside, this could be a problem when restarting the app due to a crash. In newer versions of Firebase, when using CustomActivityOnCrash, `FirebaseApp.initializeApp(this);` must be called in your `Application.onCreate`. I have updated the installation instructions accordingly.

Thanks for your report.
