### ISSUE TITLE
Wrong build date info

### ISSUE THREAD

**Issue by andresmr** [Ereza/CustomActivityOnCrash#85]
When user taps in more details, the Build Date shown is not correct, I will create a Pull request to propose a solution.

**Comment by andresmr** [comment]
Hola, em podries ajudar amb aquest issue?
Gràcies.

**Comment by Ereza** [comment]
Hi Andrés,

The problem is that the build date was properly set in older versions of the Android building tools, but was later removed. There was a workaround by using `android.keepTimestampsInApk`, but it's an experimental and unsupported flag. I fixed the code so that invalid build dates are not shown in the error details in #31 and fixed it again in the latest commits (any date before 1990 is hidden). I am considering removing the build date information completely in future versions.

I appreciate your PR #86, but instead of adding additional steps in the sample project that might end up being used by only a few people, I would instead suggest relying on the build version (that shows the versionName of your app), and if you are using internal deliveries of debug versions inside your company (or anywhere), I would suggest to add the build date to the versionName by using `versionNameSuffix "-DEV-" + new Date().format('yyyyMMdd-HHmmss')` in your `build.gradle` file.
